### ISSUE TITLE
cmd not found?

### ISSUE THREAD

**Issue by poopsieischris** [sonicrules11/Barbossa#11]
https://i.gyazo.com/03e47700f813f9bcbc3f6a2f992ba1b6.png

I compiled and then moved the thing to injector and then pasted this but it's not working?

**Comment by sonicrules11** [comment]
Did you watch the video?
Your problem is you need to change directory

PS: "I compiled and then moved the thing to injector and then pasted this but it's not working" Are you asking if its not working??? 🤔

**Comment by poopsieischris** [comment]
Yeah i watched the video

https://gyazo.com/1db2fbb232e7235ab66b86d50f7821a1

**Comment by sonicrules11** [comment]
jfc mate 
```
cd ~/Downloads/Barbossa-master/injector
```
