### ISSUE TITLE
CSGO is crashing when trying to inject

### ISSUE THREAD

**Issue by ipodib** [sonicrules11/Barbossa#14]
With latest CSGO version while injecting CSGO process is crashing. Any ways to resolve this issue or maybe help me with it?

Thanks.

**Comment by sonicrules11** [comment]
When are you injecting? In game, Menu, When starting game?

**Comment by ipodib** [comment]
When in game. I mean my steps:
1. Launch a game and wait when it full launches.
2. Inject.
3. Crash.

**Comment by ipodib** [comment]
It appears to be an issue with antivirus that is launched. Without that it's working as expected. So this one can be closed. Thanks!

**Comment by PenguinsWillLickYou** [comment]
CSGO i crashing when I try to inject. 

I put into terminal: `sudo ./dylib_injector 18923 /Users/test/Downloads/Barbossa-master/bin/libBarbossa.dylib`

But everytime, it crashes when injected. What do I do?

**Comment by sonicrules11** [comment]
What injector are you using?
Debug with Xcode.
