### ISSUE TITLE
Image not Found

### ISSUE THREAD

**Issue by holasenorhello** [sonicrules11/Barbossa#16]
Hello,

I tried the hack, using osxinj and libBarbossa.dylib

But I get this error:

module: 0x0
dlopen error: dlopen(bootstrap.dylib, 6): image not found
pid: 13359
failed to inject: module:0x0 bootstrapfn:0x0

Any help troubleshooting?

Thanks

**Comment by holasenorhello** [comment]
Nevermind, it was a stupid naming issue. But after I fixed the name to bootstrap.dylib, I get this error:

dlopen error: dlopen(bootstrap.dylib, 6): no suitable image found.  Did find:
	bootstrap.dylib: mach-o, but wrong architecture
	/Users/nathaniel0728/csgo_hacks/Barbossa/bootstrap.dylib: mach-o, but wrong architecture
pid: 13359
failed to inject: module:0x0 bootstrapfn:0x0

Any help troubelshooting?

Thanks

**Comment by holasenorhello** [comment]
Ok, I am now getting this error, after fixing above errors:

mach_inject: found threadEntry image at: 0xf5000 with size: 13568
mach_inject failing.. (os/kern) invalid address

**Comment by holasenorhello** [comment]
It seems as if the issue is that the osxinj is using i386, as opposed to the libs using x86_64 architecture. How do you compile osxinj to use the same architecture?

**Comment by sonicrules11** [comment]
Are you sure you're building it correctly
Sorry it took so long for me to reply to this.

**Comment by holasenorhello** [comment]
The link doesn't seem to work anymore - could you possibly reupload the bootstrap.dylib and osxinj? Also, should they be located in the same directory?

Thank you
