### ISSUE TITLE
help me mac os sierra not injecting

### ISSUE THREAD

**Issue by philosofonusus** [sonicrules11/Barbossa#18]
module: 0x0
dlopen error: dlopen(bootstrap.dylib, 6): image not found
pid: 11619
failed to inject: module:0x0 bootstrapfn:0x0

**Comment by jaycss** [comment]
you dont have a bootstrap.dylib file.

**Comment by philosofonusus** [comment]
yes where i can have it

**Comment by sonicrules11** [comment]
> yes where i can have it

https://github.com/scen/osxinj

**Comment by philosofonusus** [comment]
there is new problem

module: 0x78F6A950
bootstrapfn: 0xC7D50
pid: 1152
image name: /Users/philosof/Downloads/Ghost-master/bootstrap.dylib
mach_inject: found threadEntry image at: 0xc7000 with size: 9888
mach_inject failing.. (os/kern) invalid address

**Comment by sonicrules11** [comment]
Change the Architectures in osxinj and boostrap project to 64 bit.

**Comment by philosofonusus** [comment]
ok how

**Comment by philosofonusus** [comment]
help me

**Comment by philosofonusus** [comment]
please
