### ISSUE TITLE
Image not Found

### ISSUE THREAD

**Issue by philosofonusus** [sonicrules11/Barbossa#19]
module: 0x0
dlopen error: dlopen(bootstrap.dylib, 6): image not found
pid: 60096
failed to inject: module:0x0 bootstrapfn:0x0

please help me

**Comment by philosofonusus** [comment]
can you answer normally please and give me bootstrap.dylib

**Comment by philosofonusus** [comment]
help me

**Comment by philosofonusus** [comment]
help me

**Comment by sonicrules11** [comment]
This was already answered [here](https://github.com/sonicrules11/Barbossa/issues/18)
