### ISSUE TITLE
Cheat Injected, But Ingame Menu Doesn't Work

### ISSUE THREAD

**Issue by PenguinsWillLickYou** [sonicrules11/Barbossa#23]
When I inject the cheat, I get this message in the CS:GO console:

```
Barbossa version 1.4
Coded by : 
ViKiNG
Improved by :
- pwned
- Warlauke
- Bypass
- Ziwiiz

```
But, nothing is showing up in game. 

In the bvars.h file in the /Barbossa/Settings/ folder, I changed the **`bool menu               = false;      bool menu               = true; // Disables menu from displaying on injection, set to true if you want the menu to display on injection.`** to **true**, but it still wouldn't work.

**Comment by PenguinsWillLickYou** [comment]
> When I inject the cheat, I get this message in the CS:GO console:
> 
> ```
> Barbossa version 1.4
> Coded by : 
> ViKiNG
> Improved by :
> - pwned
> - Warlauke
> - Bypass
> - Ziwiiz
> ```
> But, nothing is showing up in game.
> 
> In the bvars.h file in the /Barbossa/Settings/ folder, I changed the **`bool menu = false; bool menu = true; // Disables menu from displaying on injection, set to true if you want the menu to display on injection.`** to **true**, but it still wouldn't work.

**Comment by sonicrules11** [comment]
Is it not opening ingame or on the menu?

**Comment by PenguinsWillLickYou** [comment]
Both. I've tried restarting the game, reinjecting the cheat, installing both osxinj and barbossa from scratch like the tutorial, but nothing works. I've also tried making a new Mac user, but the same issue.

**Comment by sonicrules11** [comment]
What key are you pressing?

Insecure wouldn't have done anything outside of disable vac [Only reason I use it, is so I can use my main account offline without getting kicked for being overwatched]

**Comment by PenguinsWillLickYou** [comment]
I tried the "enter" button next to my keypad.

**Comment by sonicrules11** [comment]
The key is Left Alt

**Comment by PenguinsWillLickYou** [comment]
> The key is Left Alt

Still Nothing.

**Comment by PenguinsWillLickYou** [comment]
Can it be another application interfering with the injection?

**Comment by sonicrules11** [comment]
I highly doubt it

**Comment by PenguinsWillLickYou** [comment]
Ok. I got it working. Weirdly, it only opens in casual and online matches, not offline with bots.

**Comment by sonicrules11** [comment]
I'll take a look later and see if I can figure out why its causing that
