### ISSUE TITLE
make Aimbot more legit

### ISSUE THREAD

**Issue by henrydatei** [sonicrules11/Barbossa#32]
Can you make an option for the Aimbot to be more legit? Currently the Aimbot aims always to the head which is quite obvious. I would prefer an option to make the Aimbot aims to the nearest hittable part of the enemy. That means when I only see the legs of an enemy the aimbot shoots in the legs of the enemy and doesn't try to make a headshot.

**Comment by iraizo** [comment]
this is an rage cheat dude

**Comment by henrydatei** [comment]
but it shouldn't be a problem to make it more legit. If you want to rage cheat you could just turn the "legit mode" off.

**Comment by iraizo** [comment]
if youre making a rage cheat ur not gonna add legit aimbot

**Comment by henrydatei** [comment]
is somewhere written that this is a rage cheat?

**Comment by iraizo** [comment]
Im pretty sure the owner said it on discord, also if it would be legit there would be things like radar, smoothing recoil sliders etc
