### ISSUE TITLE
help

### ISSUE THREAD

**Issue by silaslclute** [sonicrules11/Barbossa#7]
says injected dosen't inject

**Comment by SpantexTm** [comment]
What's the exact inject message your getting? Also make sure you're pressing Option (alt) to open the client.

**Comment by silaslclute** [comment]
module: 0x24025A0
bootstrapfn: 0xC8F2DD3
pid: 34546
image name: /Users/blankuser/Desktop/Hack/bootstrap.dylib
mach_inject: found threadEntry image at: 0x10c8f2000 with size: 9944
wrote param with size 46
and i am i know what im doing it j wont open or inject

**Comment by silaslclute** [comment]
lol nvm its working now lel sorry my bad

**Comment by SpantexTm** [comment]
@sonicrules11 Close

**Comment by sonicrules11** [comment]
k
