### ISSUE TITLE
Sliding

### ISSUE THREAD

**Issue by SpantexTm** [sonicrules11/Barbossa#8]
With everything on the cheat turned off I have been repeativly told that I'm sliding around the map and was wondering if this is a glitch or something that can be fixed. 

Thanks,
Spantex

**Comment by SpantexTm** [comment]
@sonicrules11 Any ideas?

**Comment by sonicrules11** [comment]
No its not a glitch its moonwalk. They only work when its off so for the time being I removed them just redownload and compile and you should be all good 

- Warlauke
