### ISSUE TITLE
Missing frameworks?

### ISSUE THREAD

**Issue by palaladas** [sonicrules11/Barbossa#9]
Hey, I can't build, because there is no frameworks file? 

it also says 6 times that a code will not execute.

Can you help ?

**Comment by SpantexTm** [comment]
"Code will not execute" is not a problem is should work anyways. However I did not get any errors building the client.

**Comment by palaladas** [comment]
I have tried a few times deleting it all and downloading again. When building, it says Build Failed and gives a lot of warnings and errors. 

I have done the before on other codes, but this one gives me trouble

**Comment by palaladas** [comment]
ld: warning: directory not found for option '-F/Users/leeviloponen/Desktop/Barbossa/Frameworks'
Undefined symbols for architecture x86_64:
  "Fakewalk(CUserCmd*, C_BaseEntity*)", referenced from:
      hacks(CUserCmd*, C_BaseEntity*, C_BaseCombatWeapon*, Vector&, bool&) in CreateMove.o
  "Moonwalk(CUserCmd*)", referenced from:
      hacks(CUserCmd*, C_BaseEntity*, C_BaseCombatWeapon*, Vector&, bool&) in CreateMove.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I don't know if this helps to clarify?

**Comment by sonicrules11** [comment]
I know whats missing i'll fix it rn

**Comment by sonicrules11** [comment]
It tells you what the problem is by the way.
Remove FakeWalk from createmove.cpp and Moonwalk
